variables:
  MAVEN_CLI_OPTS: ""
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS test

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp README.html .public/index.html
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
